### ISSUE TITLE
overflow-y

### ISSUE THREAD

**Issue by filippobrigati** [antoniopataro/dona-clone#1]
Hi this clone is 📈, i was using it and if I put a very long name, the app title doesn't wrap (on mobile)

**Comment by antoniopataro** [comment]
Hi there! I believe it is now working. 🙏

![image](https://user-images.githubusercontent.com/87823281/179054372-70f66d4a-7c28-438f-9de3-81feda28b413.png)


Had to remove `min-height` properties and take advantage of `padding`'s behaviour. 

Still a lot of work to do when it comes to mobile.

I'm closing this issue, but, if you find anything else, let me know. Thanks for helping! ❤️
