### ISSUE TITLE
Switch categories bug when responsive

### ISSUE THREAD

**Issue by devloos** [antoniopataro/dona-clone#3]
Hey Antonio,
I got two things love the look of the app... looked at Dona's actual implementation and looks very close great job! I am going to try and do the same with MEVN stack and add a bit of my taste on there ill let you know how it comes out.

Anyways on to the bug here is footage of it I am wondering if it has to do with active or non-active button states let me know if you figure it out! Also, it seems to work sometimes but not all which has me thinking it might not be the button states

https://user-images.githubusercontent.com/58356571/181096287-d299d8da-8059-43cc-82ca-712b7d9da7e5.mov

**Comment by antoniopataro** [comment]
Hey! Thanks for the feedback.

I solved it just by removing its `pointer-events` when user's width is below 1024px. However, I'm not satisfied with how it currently looks when responsive, so I'm just removing the sidebar.

I may do some tweaks in a near future, but for now that's it. 😅
